---
title: "README"
author: "Laura Herrfurth, Katharina Lotter, Kiren Nadeem, Marie Lulu Salein"
date: "19 7 2022"
output: html_document
---

# Topic 3: Proteome-wide screen for RNA-dependent proteins
## Team 5: HeLa Cells during Mitosis and Interphase


## Overview

### Experiment 

The used experimental data was obtained from experiments with HeLa cells synchronized in either interphase or mitosis.These cells were lysed and one sample was treated with RNase before both samples were applied on a sucrose gradient. After further treatment mass spectrometry was performed and the results were showed in two data sets with protein amounts for each protein in each fraction of the sucrose gradient.

### Our project

The aim of our project is to identify RNA-binding and -dependent proteins. We worked on two different data sets, one examining the RNA-protein interactome in mitosis, the other one during interphase. The procedure was the same for both of them: The experimental data was cleaned and normalized to make a comparison between the proteins possible. In a second step the reproducibility was tested by verifying if all global and local maxima do not shift more than one fraction between the three replicates of each condition. After testing reproducibility the x-shifting proteins in global and/or local maximum were identified and the significance of the shift was tested. Subsequently properties of both date sets were compared and the model of a linear relation between the correlation of the two different samples and their x-shift was examined.

## Getting started

### Preparation

In order to execute the code, you need to save both our data sets first. It will be necessary to insert your own directory at the beginning of both Markdowns xxxxxxxx Dateinnamen einfügen xxxxxxxx to load the data in R. 

### Executing program

Start with executing the xxxxxxxxMitosis. The code consists of the data cleanup, normalization, maxima and shift determination and testing for the mitosis data set.
The code for the interphase data set includes, next to all the parts mentioned for the mitosis markdown, the k-means clustering and the linear regression analysis we performed. For k-means clustering, R has to access data from the mitosis data set analysis which is why it is essential to keep the data after the execution of the first code in the R environment.

## Team members

- Laura Herrfurth
- Katharina Lotter
- Kiren Nadeem
- Marie Lulu Salein